### ISSUE TITLE
Implementing PROPFIND

### ISSUE THREAD

**Issue by ronslow** [cch1/http.async.client#20]
Fantastic library. Thanks.

How would I extend to the PROPFIND method.

I am thinking along the lines of

(gen-method :propfind)

(def client (create-client client :auth {:user "user" :password "password"}))

(def body-string  "<?xml version=\"1.0\" encoding=\"utf-8\" ?>
   <D:propfind xmlns:D=\"DAV:\">
     <D:prop>
          <displayname/>
         
     </D:prop>
   </D:propfind>")

(ignore GITHub's reformatting here - this is a propfind xml query in the body of the request)

(PROPFIND client "http://someurle.com/something" :headers {:content-type "text/xml"} :body body-string)

But I am getting NPE at  com.ning.http.client.RequestBuilderBase.allowBody(RequestBuilderBase.java:564)
because the request has got no method associated with it.

Could you help me with this?

Thanks

Robert

**Comment by cch1** [comment]
Any more input, @ronslow?  If not, I'm going to close this issue.

**Comment by ronslow** [comment]
No thanks CCH1. Let's close the issue.
