### ISSUE TITLE
Autoqueueing of Connections

### ISSUE THREAD

**Issue by angerman** [cch1/http.async.client#33]
**Fequrerequest**: When dealing with a source of urls, calling `(c/GET client url)` for each url would be convenient. If the client could be configured to the maximum concurrent request to fullfil, the returned promises would just block until the url was requested and taken off the queue.

**Comment by cch1** [comment]
Without a strong use case, I'm going to leave this for callers to implement themselves.  The semantics of handling multiple exceptions and even correlating responses (and exceptions) to URLs could be too varied to warrant a single implementation.
