### ISSUE TITLE
Client connection pool

### ISSUE THREAD

**Issue by thiagotnunes** [cch1/http.async.client#50]
It was mentioned before that it is not very efficient to create a client per request, do you have any idea of a best approach for this? Maybe a connection pool?

**Comment by cch1** [comment]
The advice offered by @neotyk above is accurate.  In fact, [there is a thread](https://groups.google.com/forum/#!searchin/asynchttpclient/pool/asynchttpclient/-sCBrIwgvqE/ncK94UTz3a0J) on the AsyncHttpClient mailing list supporting this position.
