### ISSUE TITLE
ning dependency is outdated

### ISSUE THREAD

**Issue by cch1** [cch1/http.async.client#54]
com.ning/async-http-client is up to version 1.7.21 and the released versino of this library depends on 1.7.10.  The transitive dependency to io.netty/netty is for "3.4.4.Final" -that library would be updated to "3.6.6.Final".

We are experiencing strange TCP connection issues and hope that such an update will resolve them.

**Comment by cch1** [comment]
Now that https://github.com/AsyncHttpClient/async-http-client has been stable on version 1.9.x for a while (since last July 2014), and now that the blocking issue for this Clojure issue has been resolved, can we please get an upgrade for the ning dependency?

**Comment by smnirven** [comment]
@neotyk Any thoughts on this? Would be great to get the ning dependency upgraded. Don't want to see this die on the vine.

**Comment by cch1** [comment]
For anyone who is follwing this issue, here is the current status: I have a branch on my fork that updates Clojure to 1.6 and AHC to 1.8.16.  There is one failing test dealing with the `http.async.client/raw-url` function backed by the AHC `getRawUrl` method.  I don't see a way to resolve this bug without updated AHC to at least version 1.9.x -and that will take a bit longer.  I hope to soon release an 0.5.3-SNAPSHOT version with this failing test so that we can get some eyes on the other changes required to update this library.

**Comment by cch1** [comment]
Another status update: Version 0.6.0 of http.async.client updates the ning depdency to 1.8.16 -the latest 1.8.X version.  It is almost completely backwards compatible with the 0.5.3 version of http.async.client with the minor exception of the deprecated `raw-url` function which has now been removed.

**Comment by cch1** [comment]
This issue is *finally* resolved and the ning AHC dependency is completely up-to-date.  Thanks @pbostrom !
