### ISSUE TITLE
Example in 'Getting Started' fails with clojure 1.7

### ISSUE THREAD

**Issue by paulrd** [cch1/http.async.client#62]
I using http.async.client 0.6.0 with clojure 1.7. I get the following error when I execute this code (returns nil):

```clojure
(with-open [client (http/create-client)] ; Create client
  (let [response (http/GET client "http://github.com/neotyk/http.async.client/")] ; request http resource
    (-> response
        http/await     ; wait for response to be received
        http/string))) ; read body of response as string
```

(http/error *1):
1. Unhandled java.lang.NullPointerException
   (No message)

                      core.clj: 7231  clojure.core/realized?
                    client.clj:  195  http.async.client/failed?
                    client.clj:  286  http.async.client/error

Problem seems to be with http/string as leaving that call out makes things ok.

**Comment by paulrd** [comment]
Oh nevermind, I wasn't using *1 properly. It has to be a response map - obviously! But there is still the strange issue of getting a nil body for github.com while google.ca works just fine. Perhaps there is something strange about github. It seems to be returning status :code 301 :msg "moved permanently" and :body of nil. In any case, you might want to put a different example in the getting started doc, or advise. Thanks!

**Comment by paulrd** [comment]
Haha! I found the problem. The getting started guide needs to change the github url from 'http://' to 'https://'! Then it works as advertised. :-/

**Comment by cch1** [comment]
Thanks Paul!
