### ISSUE TITLE
Websockets in v1.0.0 are broken: websocket calls upgrade-handler with list instead of unrolled args

### ISSUE THREAD

**Issue by timmc** [cch1/http.async.client#66]
Your README advertises v1.0.0 as the latest release (based on Clojars), but it doesn't work.

In https://github.com/cch1/http.async.client/blob/v1.0.0/src/clj/http/async/client.clj#L311 `websocket` has a list of options e.g. `(:open fn :close fn)` and calls `upgrade-handler`, which is expecting unrolled args: https://github.com/cch1/http.async.client/blob/v1.0.0/src/clj/http/async/client/websocket.clj#L101

**Comment by pbostrom** [comment]
Sorry, the websocket client still needs some work. I should have this fixed in a couple of days.

**Comment by pbostrom** [comment]
Fixed with 94e73e4, v1.0.1 is deployed on Clojars. Thanks for testing this out.

**Comment by timmc** [comment]
Ah, thanks!
