### ISSUE TITLE
Cannot create SSLContext with default keystore

### ISSUE THREAD

**Issue by daveliepmann** [cch1/http.async.client#70]
From the defn of `ssl-context`:

>If [:keystore-file] is empty, will use default keystore.

Passing `nil` or `""` for this parameter, or not passing it at all, results in:

>java.io.FileNotFoundException
>   File or resource "" could not be found.

**Comment by cch1** [comment]
Confirmed

**Comment by cch1** [comment]
Commit 552be4421bac7b3a02ff49156a4bef55429240fd should resolve the problem.  I've added tests so that we don't run into this again.

**Comment by daveliepmann** [comment]
Well that is super-duper. Thank you!
