### ISSUE TITLE
Packet Size limit?

### ISSUE THREAD

**Issue by eslachance** [cch1/http.async.client#80]
I'm having an issue with packets not being received by the websocket *client*. Basically the issue is that I'm receiving packets that seem to be dropped by the socket completely, while other packets are going through. 

The packets that are dropped are... "large", I guess, in terms of socket. They can contain something like 2000 entries in a JSON file, many - many - k's. I do believe these are compressed, and I can't seem to find any reference to compression in the library code. Disabling compression closes the websocket when a large packet is received.

Note that when I say "large" I mean that, for instance, a very *very* small packet I'm receiving measures around 11k (11070 characters). I will be receiving **much** larger than this.

**Comment by cch1** [comment]
Unfortunately we don't have any practical experience using the underlying Java websockets implementation.  I would happily accept pull requests that address your concern.  BTW, you might try asking questions here: https://groups.google.com/forum/#!forum/asynchttpclient

**Comment by eslachance** [comment]
Unfortunately, while barely have the know-how to *use* a library, I don't have nearly enough experience to figure out the underpinnings of the Java lib that's used. In the end I had to do with Aleph, which does handle these packets (I had to decompress them myself, but still!).

Thank you for your time!
